# =========================================
# Docker Compose for Development Environment
# =========================================
version: '3.8'

services:
  # Next.js Application
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NODE_VERSION=20.18.0
        - ALPINE_VERSION=3.20
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: dominate-leads-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - DOCKER_CONTAINER=true
      - PERFORMANCE_LOG_STDOUT=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory for debugging
      - ./logs:/app/logs:rw
    networks:
      - app-network

  # Optional: Nginx reverse proxy for production-like setup
  nginx:
    image: nginx:alpine3.20
    container_name: dominate-leads-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if available
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nextjs-app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local